repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
      exclude: ^tmp/
      language_version: python3
-   repo: https://github.com/PYCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      exclude: ^(tmp/|docs/)
      args: ['--max-line-length=88', '--extend-ignore=E203']
