name: Documentation

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

defaults:
    run:
        # See https://github.com/mamba-org/provision-with-micromamba#important
        shell: bash -l {0}

jobs:
    docs:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout Git repository
              uses: actions/checkout@v3

            - name: Install Conda environment with Micromamba
              uses: mamba-org/setup-micromamba@main
              with:
                  cache-downloads: true
                  cache-env: true
                  environment-file: environment.yaml
                  environment-name: yomixenv

            - name: Install PyPI dependencies
              run: |
                  pip install furo sphinx sphinx-autodoc-typehints sphinx-mathjax-offline

            - name: Build documentation
              run: |
                  sphinx-build docs/source _build
                  touch _build/.nojekyll
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
              with:
                  publish_branch: gh-pages
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: _build/
                  force_orphan: true
